일본 번역 적용
carpenstreet/blender-translations pull request #58
Opened 2023-06-14 01:53 UTC by Youdiie

## 관련 링크

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-384)

## 발제/내용

- 일본어 번역 추가

## 대응

### 어떤 조치를 취했나요?

- SW사업팀에서 번역 요청한 [시트](https://docs.google.com/spreadsheets/d/1P6j92vLo7_r-7AkoT3ainxoBY8T0pHtbItQBdNh1PVk/edit#gid=1266308071) 토대로 추가
- 0.3.5에 추가되는 항목은 하단에 미번역 상태로 추가

2023-06-14 04:30 UTC, sdkfile requested changes
일단 기록을 위해 남겨둡니다 @Youdiie

2023-06-14 04:30 UTC, sdkfile commented on po/ja.po
> +# msgstr "에이콘3D 보정예시 보러가기"
빠진거 여기부터 남겨볼게요

2023-06-14 04:30 UTC, sdkfile commented on po/ja.po
> +# msgstr "에이콘3D 보정예시 보러가기"
msgctxt "abler"
msgid "Layers"
msgstr "レイアー"

2023-06-14 04:30 UTC, sdkfile commented on po/ja.po
> +# msgstr "에이콘3D 보정예시 보러가기"
msgctxt "abler"
msgid "ACON3D Asset Store"
msgstr "ACON3Dアセットストア"

2023-06-14 04:30 UTC, sdkfile commented on po/ja.po
> +# msgstr "에이콘3D 보정예시 보러가기"
msgctxt "abler"
msgid "Buy 3D assets"
msgstr "3Dアセット購入"

2023-06-14 04:30 UTC, sdkfile commented on po/ja.po
> +# msgstr "에이콘3D 보정예시 보러가기"
<img width="1215" alt="스크린샷 2023-06-14 오후 1 29 38" src="https://github.com/carpenstreet/blender-translations/assets/43770096/fb0e7555-d976-4cb6-8efc-9f5d3d2bd939">

여기 있는거 정리해서 넣어야겠네요 (Fly mode 시 아래 바)

2023-06-14 04:56 UTC, sdkfile commented on po/ja.po
> +# msgstr "에이콘3D 보정예시 보러가기"
저 이미지에 있는거는 아예 번역이 안되네요 ㄷㄷ

2023-06-14 05:17 UTC, sdkfile commented
이제 남은거: 레이어 추가 + 조명 추가 기능에 대한 일문 번역 + (한글 번역도 챙겨야함)

2023-06-14 06:10 UTC, sdkfile commented
@Youdiie 누락된거 추가 완료되면 말씀해주세용

2023-06-14 06:36 UTC, sdkfile commented
누락된 번역 추가 완료

2023-06-16 05:06 UTC, sdkfile approved these changes
@Youdiie 
마무리 완료했습니다.

2023-06-16 05:51 UTC, Youdiie commented
@sdkfile 저두 빌드해서 잘 들어간거 확인했습니다~

2023-06-16 05:52 UTC, merged