Feature/swtask 416 update japanese
carpenstreet/blender-translations pull request #60
Opened 2023-06-21 08:07 UTC by Youdiie

## 관련 링크

[링크](https://carpenstreet.atlassian.net/browse/SWTASK-416)

## 발제/내용

- 번역 누락 코드 추가

## 대응

### 어떤 조치를 취했나요?

-

2023-06-22 06:15 UTC, sdkfile requested changes
매우 작은 변경사항입니다 @Youdiie

2023-06-22 06:15 UTC, sdkfile commented on po/ja.po
> +msgstr "Acon3Dアカウントでログインしてください。"
여기 ACON3D로 바꿔주시면 될 것 같습니다~

2023-06-22 06:52 UTC, Youdiie commented on po/ja.po
> +msgstr "Acon3Dアカウントでログインしてください。"
수정했습니다~

2023-06-23 01:32 UTC, sdkfile approved these changes

2023-06-23 01:33 UTC, merged