3D커서기반 조명생성기능 한글 번역추가
carpenstreet/blender-translations pull request #62
Opened 2023-08-01 05:06 UTC by LeoParkProDev

아래에 이미지처럼 되도록 한글 번역 추가

<img width="300" alt="스크린샷 2023-08-01 오후 2 06 10" src="https://github.com/carpenstreet/blender-translations/assets/130434011/4b0220b9-fc98-4281-86ba-e486b89c11cb">

2023-08-01 05:07 UTC, JJong84 commented
@LeoParkProDev 일본어 번역은 따로 브랜치 생성해서 추가하실 예정일까요? (cc. @sdkfile)

2023-08-01 05:15 UTC, sdkfile requested changes
@LeoParkProDev 이거 일본어 번역도 추가합시다!

"3Dカーソル位置に照明を生成します"

2023-08-01 12:51 UTC, LeoParkProDev commented
@sdkfile 추가하였습니당!

2023-08-02 01:40 UTC, sdkfile approved these changes

2023-08-02 01:41 UTC, JJong84 approved these changes

2023-08-02 02:14 UTC, merged